### ISSUE TITLE
README.md: 'customization' link is broken

### ISSUE THREAD

**Issue by megakoko** [tangem/tangem-sdk-ios#120]
The 'c' is cyrillic. See attached screenshot:

<img width="641" alt="Screenshot 2021-11-27 at 11 48 51" src="https://user-images.githubusercontent.com/12209839/143673141-262b10f1-fdc9-4698-82df-1086b7eb49ea.png">

**Comment by megakoko** [comment]
A simple `grep` command can be added to the lint / build server to avoid confusion.

**Comment by tureck1y** [comment]
closed by #125
