### ISSUE TITLE
Install without CocoaPods

### ISSUE THREAD

**Issue by muratogat** [tangem/tangem-sdk-ios#190]
Is there a way to add the library without using CocoaPods?
Currently the preferred way to manage dependencies on iOS is Swift Package Manager. Would you be able to add SPM support?
Otherwise please either release a .framework file that can directly be imported, or direct me towards a guide that can be used to import the SDK through the source code.
Thanks.

**Comment by tureck1y** [comment]
Yes, we have plans to add SPM support shortly. Unfortunately, we are a bit overwhelmed right now and I can't provide exact dates.

**Comment by muratogat** [comment]
More than 1 year and this is the only pod in my project :)
Can't you at least add an already build .framework to the release products, so one could simply drag it into the Frameworks folder instead of using CocoaPods? Does it need to be built from source every time?

**Comment by tureck1y** [comment]
Almost done https://github.com/tangem/tangem-sdk-ios/pull/333

**Comment by muratogat** [comment]
Meanwhile I already started to build from source, but this is welcome anyway :)
