### ISSUE TITLE
WalletConnect V2 issues

### ISSUE THREAD

**Issue by py9mrg** [tangem/tangem-sdk-ios#312]
Hello,

I am trying to connect to dapp.1inch.io using wallet connect V2 and it is not working. The Tangem app gets opened as it should, I click start, but then when I go back to dapp.1inch.io it keeps trying to open the Tangem app presumably because it hasn’t received the message correctly. If I click cancel rather than open, I get the message:

    Safari cannot open the page because the address is invalid.
    
I have tried both in Safari as above and also Brave. Neither works. 

Edit: strangely, I can appear to see something going on underneath the warning that implies the connection has worked. But something between the app and website is amiss. 

Thanks.

**Comment by tureck1y** [comment]
This task relates to the [application](https://github.com/tangem/tangem-app-ios), not to the SDK, but we will check and return with an answer. Thank you

**Comment by tureck1y** [comment]
We checked connection with app.1inch.io and it's ok.
