### ISSUE TITLE
20 second session timeout

### ISSUE THREAD

**Issue by DrenImeraj** [tangem/tangem-sdk-ios#345]
There seems to be a 20 second session timeout on iOS. When signing hashes using a 30 second "Long tap" security delay, the session times out after 20 seconds and throws a "readerSessionInvalidationErrorSessionTerminatedUnexpectedly" error. 

Any workarounds for this issue?

**Comment by DrenImeraj** [comment]
iOS: 17.4.1
Device: iPhone 14 Pro Max

Here's some additional details:
- This issue does not occur when using the production Tangem app, only when using the SDK. 
- The SDK is being used through the "tangem-sdk-react-native" package on React Native.
- SDK versions 3.4.0 (default on the package) and 3.8.0 have been tested.
- The issue does not seem to be related to the "Long tap" countdown. If the card is briefly moved away so that the countdown stops, the error will be thrown earlier. This seems to imply that there's a 20 second timeout from the moment the communication starts.
- This issue is not present on Android.

**Comment by tureck1y** [comment]
Thank you for the detailed explanation!

This is an iOS-specific issue with the newest iPhones on iOS 17+. We implemented a workaround for it at 3.9.0.
tangem-sdk-react-native is outdated and no longer maintained. You can try to update TangemSdk version here https://github.com/tangem/tangem-sdk-react-native/blob/main/tangem-sdk-react-native.podspec
