### ISSUE TITLE
Support for walletconnect on ethereum?

### ISSUE THREAD

**Issue by shunkakinoki** [tangem/tangem-sdk-ios#94]
Hi tangem team,
I'm considering a purchase of the Tangem Multicurrency Hardware Wallet Pack
I wanted to ask if there is support for walletconnect on the iPhone app. (This is the only thing that's stopping me)

**Comment by lazutkin-andrey** [comment]
We do support wallet connect in Tangem app. Sdk provides only API for working with Tangem card.
